### PR TITLE
Bump policyengine-core

### LINKED ISSUE #798: Bump policyengine-core to 2.11.3
To capture randomness bug fixes

### PR DESCRIPTION
**Pull request by MaxGhenis**
Fixes #798

### CODE REVIEW

**Comment by MaxGhenis** [comment]
@nikhilwoodruff can you look into why bumping core would affect these test results?

**Comment by nikhilwoodruff** [comment]
Ah I think the random seed changing would do that

**Comment by nikhilwoodruff** [comment]
Removed MTRs from those tests since I don't think it made sense anyway (we're testing small employment income increases from zero when self-employment is the income source)

**Review by nikhilwoodruff — APPROVED** [review]

**Comment by nikhilwoodruff** [comment]
Passing non-microdata tests so merging.

**Pull request merged**
