### PR TITLE
Updated values for 'universal_credit'

### PR DESCRIPTION
**Pull request by Kittyaoooo**
* Tax and benefit system evolution. 
* Impacted periods: all. | until 2023-04-09. | from 2016-04-10.
* Impacted areas: `policyengine_uk/parameters/gov/dwp/universal_credit`
* Details:
  - Updated values for 'universal_credit'

- - - -

These changes _(remove lines which are not relevant to your contribution)_:

- Fix or improve an already existing calculation.

### CODE REVIEW

**Comment by nikhilwoodruff** [comment]
Thanks @Kittyaoooo - could you please add in a `changelog_entry.yaml` entry? All the previous PRs that have been merged have it if you need an example.

**Comment by Kittyaoooo** [comment]
plz check it.

**Comment by nikhilwoodruff** [comment]
Thanks- nearly there, could you just remove the `.idea` folder your last commit added? Think that might be from your editor.

**Comment by Kittyaoooo** [comment]
sorry, please check it again.

**Pull request merged**
