### PR TITLE
SPI validation fixes

### LINKED ISSUE #918: Fix Scottish rates for 2020/21
These are currently calculated incorrectly

### LINKED ISSUE #919: Add documentation page on SPI validation

### PR DESCRIPTION
**Pull request by anth-volk**
Fixes #918. 
Fixes #919. 

This PR raises the PolicyEngine UK model's convergence with the SPI's 2020/21 data. This PR also introduces a documentation page (currently a draft requiring some clarification) that describes the validation exercise, as well as areas where the two models diverge.

### CODE REVIEW

**Comment by anth-volk** [comment]
Absolute error measurement as of commit https://github.com/PolicyEngine/policyengine-uk/pull/914/commits/c2039ef54c4279c3d0e9b83e9503b90590f7d499:
```
<=10      91.461733
<1000      5.525746
>=1000     1.865212
<100       1.147309
```

**Comment by anth-volk** [comment]
Absolute error measurement as of commit https://github.com/PolicyEngine/policyengine-uk/pull/914/commits/581569b8b4ca3acffa52efd66e1c5aa85d2bcf8a:
```
<=10      92.685731
<1000      4.806584
>=1000     1.671160
<100       0.836525
```

**Comment by anth-volk** [comment]
Absolute error measurement as of https://github.com/PolicyEngine/policyengine-uk/pull/914/commits/ee35212072dd462209f044ad992e4c438494d86b:
```
<=10      92.695427
<1000      4.807466
>=1000     1.670153
<100       0.826954
```

**Comment by anth-volk** [comment]
Absolute error as of https://github.com/PolicyEngine/policyengine-uk/pull/914/commits/c974b4243b325225a3c1ee7f46c04a12710b8634:
```
<=10      92.685731
<1000      4.806584
>=1000     1.671160
<100       0.836525
```

**Review by nikhilwoodruff — APPROVED** [review]

**Pull request merged**
